---
# =============================================================================
# Default variables for the System Config role
# =============================================================================

# --- Users and groups ---
sys_user: aether
sys_uid: 1005

sys_group: aether
sys_gid: 1005

# --- Logs ---
logs_path: /var/log
rotate_path: /etc/logrotate.d

# --- Paths ---
temp_path: /tmp
