---
# =============================================================================
# Default variables for the NFS Setup role
# =============================================================================

# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------
nfs_export_path: /dwh
nfs_mount_path: /warehouse

# ------------------------------------------------------------------------------
# Network identifiers
# ------------------------------------------------------------------------------
# Adjust according to your real IPs
nfs_server_ip: "{{ hostvars['aether-publish']['ansible_host'] }}"
nfs_allowed_clients: "{{ hostvars['aether-process']['ansible_host'] }}"

# ------------------------------------------------------------------------------
# Folders owner
# ------------------------------------------------------------------------------
sys_user: aether
sys_group: aether
