---
# =============================================================================
# Default variables for the Aether API role
# =============================================================================

# --- System and Permissions ---
sys_user: aether
sys_group: aether

# --- Application Repository ---
api_repo_url: "https://github.com/rabanedo/tfe-aether.git"
api_repo_version: "main"

# --- Path cdse-api ---
api_base_dir: /opt/cdse-api

# --- Directory Structure (Data Warehouse) ---
# List of folders required by the application to process products.
# Extracted to a variable to allow deployments to different disks or paths.
api_dwh_directories:
  - /dwh/products/S2/derived_products/NDVIb
  - /dwh/products/S2/derived_products/RGB1184
  - /dwh/products/S2/derived_products/NDVIb_mosaic
  - /dwh/products/S2/derived_products/RGB1184_mosaic
  - /dwh/products/S2/original_products
  - /dwh/tmp

s2_tmp_path: /warehouse/tmp
