---
- name: Run NFS Server (Publish) tasks
  ansible.builtin.include_tasks: server.yml
  when: "'publish' in group_names"

- name: Execute NFS Client tasks (Process)
  ansible.builtin.include_tasks: client.yml
  when: "'process' in group_names"
