[process]
aether-process ansible_host=192.168.1.223 ansible_user=aether

[publish]
aether-publish ansible_host=192.168.1.224 ansible_user=aether

[all:vars]
ansible_python_interpreter=/usr/bin/python3
